### ISSUE TITLE
How to know ports and protocols?

### ISSUE THREAD

**Issue by marcmascarell** [jacklul/q3serverlist#1]
Hi,

Where can I find information about prots and protocols?

RIght now I tried some combinations with some ports but without success.

```php
new MasterServer('codmaster.activision.com', 28960, 26);
```

Thanks

**Comment by jacklul** [comment]
I believe the port varies on the game, for example Q3 is using 27950 and Jedi Academy 29060, the protocol value will also be different in every game as that is internal game versioning. I don't think there is much information about it except that what you can extract from the game itself.
Another approach would be software like Wireshark and capturing network connections.

Master server address is usually resolved on game/server start, it should have clear line like "master.xxxxxxxx.com resolved to x.x.x.x:PORT" in the console, the protocol version can be usually extract by reading "protocol" cvar value in game console.

`codmaster.activision.com` is using ports 20510 (CoD), 20710 (CoD2) or 20810 (CoD4 - unsupported). You will still have to figure out the protocol number. For CoD it's 1.

`->getServers()` allows you to set timeout (which by default is one second and might be too low sometimes), you could try `->getServers('', 3)` or even higher numbers (note that the script will wait for that long for the reply even if the master server already sent all the packets).

**Comment by marcmascarell** [comment]
Hi jacklul,

Good explanation, but Im not being able to fetch servers with the port and protocol you gave me, even changing timeout to a long one. Im using the exact same code that its in the readme but with this change:

```php
$ms = new MasterServer('codmaster.activision.com', 20510, 1);
$servers = $ms->getServers('', 15);
```

Thanks again

**Comment by jacklul** [comment]
The same exact code works on my end though.
Are you trying this from your local machine or shared webhosting ? Sockets extension might be disabled or UDP connections are blocked, this library can't work without this.

**Comment by marcmascarell** [comment]
Sorry I just noticed this:

```php
 && $info['game'] === 'japlus'
```

Now its working fine. Thank you very much!

**Comment by jacklul** [comment]
Yeah, that was example specific for Jedi Academy. 
Glad it works now!
